"""empty message

Revision ID: 892e247f6c8a
Revises: bdb0f70aac44
Create Date: 2019-03-13 21:55:29.062842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892e247f6c8a'
down_revision = 'bdb0f70aac44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('categoryname', sa.String(length=40), nullable=True))
    op.add_column('product', sa.Column('unitname', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'unitname')
    op.drop_column('product', 'categoryname')
    # ### end Alembic commands ###
