"""empty message

Revision ID: a350ad53a6bd
Revises: 9141272f68ad
Create Date: 2019-05-31 14:28:24.169088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a350ad53a6bd'
down_revision = '9141272f68ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('barcolor', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'barcolor')
    # ### end Alembic commands ###
