"""empty message

Revision ID: bdb0f70aac44
Revises: cb6673e838bf
Create Date: 2019-03-03 23:52:03.951794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb0f70aac44'
down_revision = 'cb6673e838bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger', sa.Column('undername', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger', 'undername')
    # ### end Alembic commands ###
