"""empty message

Revision ID: eacb94fc5641
Revises: db82ee9762e4
Create Date: 2019-02-19 15:16:28.566444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacb94fc5641'
down_revision = 'db82ee9762e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'email')
    # ### end Alembic commands ###
